# Configuring Rustfmt
# https://rust-lang.github.io/rustfmt/?version=v2.0.0-rc.2

# Misc
edition = "2018"
version = "Two"
unstable_features = true

# Fundamental stuff
newline_style = "unix"
combine_control_expr = false
#fn_params_layout = "Vertical"
force_multiline_blocks = true
match_block_trailing_comma = true
overflow_delimited_expr = true
use_field_init_shorthand = true
#where_single_line = true

# comments
format_code_in_doc_comments = true
normalize_comments = true
#wrap_comments = true

# Imports
group_imports = "StdExternalCrate"
imports_granularity = "Crate"

# Ordering
reorder_impl_items = true
reorder_imports = true

# Options that can change the source code beyond whitespace/blocks
merge_derives = true

# Marco
format_macro_matchers = true
format_macro_bodies = true

# Control options
# report_fixme="Unnumbered"
# report_todo="Unnumbered"
